language: python
python:
    - "3.6"

env:
    - SECRET_KEY=foo
    - DJANGO_SETTINGS_MODULE=pico.settings

install:
    - pip install -r requirements.txt
    - pip install pytest-django pytest-asyncio pytest-cov coveralls

script:
    - py.test --cov pico pico

after_success:
    coveralls
