language: python
python:
    - "3.6"

env:
    - SECRET_KEY=foo

install:
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - coverage run --source=pico manage.py test

after_success:
    coveralls
