site_name: Pico
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust

nav:
    - Home: index.md
    - Install: install.md
    - Configure: configure.md
