# Generated by Django 3.0.2 on 2020-01-31 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pico.projects.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=16, unique=True)),
                ('artwork', models.ImageField(upload_to=pico.projects.helpers.upload_project_image)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated',),
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='projects.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__last_name', 'user__first_name', 'user__email', 'project__name'),
                'unique_together': {('user', 'project')},
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='projects.Manager')),
            ],
            options={
                'unique_together': {('code', 'manager')},
            },
        ),
        migrations.CreateModel(
            name='DirectoryListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory', models.CharField(choices=[('apple', 'Apple Podcasts'), ('deezer', 'Deezer'), ('google', 'Google Podcasts'), ('spotify', 'Spotify'), ('stitcher', 'Stitcher'), ('tunein', 'TuneIn')], max_length=10)),
                ('url', models.URLField(max_length=512, verbose_name='URL')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directory_listings', to='projects.Project')),
            ],
            options={
                'ordering': ('directory', 'project__name'),
                'unique_together': {('directory', 'project')},
            },
        ),
    ]
