# Generated by Django 3.0.2 on 2020-02-01 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('due', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='projects.Project')),
            ],
            options={
                'ordering': ('-updated',),
                'get_latest_by': 'created',
                'unique_together': {('slug', 'project')},
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kanban.Card')),
                ('deliverable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Deliverable')),
            ],
            bases=('kanban.card',),
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kanban.Board')),
                ('slug', models.SlugField(max_length=100)),
                ('default', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='projects.Project')),
            ],
            options={
                'ordering': ('-default', 'name'),
                'unique_together': {('slug', 'project')},
            },
            bases=('kanban.board',),
        ),
    ]
