# Generated by Django 3.0.2 on 2020-02-05 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pico.projects.helpers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_task_tasktag'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_categories', to='projects.Project')),
            ],
            options={
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='EvidencePiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('mime_tyoe', models.CharField(max_length=100)),
                ('media', models.FileField(blank=True, max_length=255, null=True, upload_to=pico.projects.helpers.upload_evidence)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces', to='projects.EvidenceCategory')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to=settings.AUTH_USER_MODEL)),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='projects.Deliverable')),
            ],
            options={
                'ordering': ('-created',),
                'get_latest_by': 'created',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='evidence_direction',
            field=models.CharField(blank=True, choices=[('up', 'up'), ('down', 'down')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='evidence_direction',
            field=models.CharField(blank=True, choices=[('up', 'up'), ('down', 'down')], max_length=4, null=True),
        ),
        migrations.CreateModel(
            name='TaskTemplateEvidenceTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_tags', to='projects.TaskTemplate')),
            ],
            options={
                'unique_together': {('tag', 'template')},
            },
        ),
        migrations.CreateModel(
            name='TaskEvidenceTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_tags', to='projects.Task')),
            ],
            options={
                'unique_together': {('tag', 'task')},
            },
        ),
        migrations.CreateModel(
            name='EvidenceTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='projects.EvidencePiece')),
            ],
            options={
                'unique_together': {('tag', 'piece')},
            },
        ),
        migrations.CreateModel(
            name='EvidenceCategoryTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='projects.EvidenceCategory')),
            ],
            options={
                'unique_together': {('tag', 'category')},
            },
        ),
    ]
