# Generated by Django 3.0.2 on 2020-02-08 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    Deliverable = apps.get_model('projects.Deliverable')
    Stream = apps.get_model('activity.Stream')

    for deliverable in Deliverable.objects.all():
        deliverable.activity = Stream.objects.create()
        deliverable.save()

        for manager in deliverable.project.managers.all():
            deliverable.activity.participants.add(manager.user)


def backwards(apps, schema_editor):
    Stream = apps.get_model('activity.Stream')
    Stream.objects.filter(deliverables__isnull=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0001_initial'),
        ('projects', '0006_auto_20200205_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverables', to='activity.Stream'),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(forwards, backwards)
    ]
