# Generated by Django 3.0.2 on 2020-02-09 09:37

from django.db import migrations, models
import pico.projects.helpers
import pico.projects.storage


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200208_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencepiece',
            name='media',
            field=models.FileField(blank=True, max_length=255, null=True, storage=pico.projects.storage.EvidenceStorage(), upload_to=pico.projects.helpers.upload_evidence),
        ),
    ]
